site_name: Tupã Framework
site_url: https://github.com/Iuptec/tupa
nav:
  - Inicio Rápido: index.md
  - Registrando novas rotas: getting_started.md
  - Routes Manager: routes_manager.md
  - Params e Query Params: params.md
  - Middlewares: middlewares.md
  - Global Middlewares: global_middlewares.md
  - After Middlewares: after_middlewares.md
  - Context: context.md
  - Exemplos: examples.md
  - Contribua: contributing.md
  - Licença: license.md
  - Sobre: about.md
theme:
  name: "material"
  features:
    - content.code.copy

plugins:
- search
- mkdocstrings

extra_css:
  - css/extra.css

markdown_extensions:
  - pymdownx.highlight:
      pygments_style: monokai
